---
# tasks file for xcat-provision
- name: define groups
  command:
    argv:
      - mkdef
      - -t
      - group
      - -f
      - "{{ item.name }}"
  loop: "{{ Xcat_groups }}"

- name: define node
  command:
    argv:
      - mkdef
      - -t
      - node
      - -f
      - "{{ item.name }}"
      - ip={{ item.ip }}
      - mac={{ item.mac }}
      - arch={{ item.arch }}
      - groups={{ item.groups }}
      - netboot={{ item.netboot }}

  loop: "{{ Xcat_nodes }}"

- name: postscript
  command:
    argv:
      - chdef
      - "{{ item.name }}"
      - postscripts=syslog,remoteshell,syncfiles,{{ item.postscripts | default() }}
  loop: "{{ Xcat_nodes }}"

- name: copy postscripts to /install/postscripts
  copy:
    src: postscripts/
    dest: /install/postscripts/

- name: configure passwords
  command:
    argv:
      - chtab
      - key=system
      - passwd.username={{ system_user.user }}
      - passwd.password={{ system_user.passwd }}

- name: edit site table
  command:
    argv:
      - chdef
      - -t
      - site
      - nameservers={{ ansible_default_ipv4.address }}
      - forwarders={{ site.forwarders }}
      - gateway={{ site.gateway }}

- name: sets up /etc/hosts from the xCAT hosts table
  command: makehosts

- name: setup named configuration
  command: makedns -n
  notify: restart named

- name: update DHCP configuration files
  command: makedhcp -n
  notify: restart dhcpd

- name: Copy os ISOs to mangement node
  copy:
    src:  "{{ item }}"
    dest: "{{ osimages_dest }}"
  loop: "{{ osimages_paths }}"

- name: create osimage
  command:
    argv:
      - copycds
      - -w
      - "{{ item | basename  }}"
    chdir: "{{ osimages_dest }}"
  loop: "{{ osimages_paths }}"


- name: create osimages
  include_tasks: set_osimage.yml
  loop: "{{ Xcat_nodes }}"




