- name: select image
  shell: lsdef -t osimage | cut -d" "  -f1 | grep  -e "{{ item.os }}".*"{{ item.mode }}"
  register: r

- name:  Generates a stateless image to be used for a diskless install
  command:
    argv:
      - genimage
      - "{{ r.stdout }}"
  when: item.mode == "netboot"

- name:  Packing a stateless image
  command:
    argv:
      - packimage
      - "{{ r.stdout }}"
  when: item.mode == "netboot"

- name: set os and installation type
  command:
    argv:
      - nodeset
      - "{{ item.name }}"
      - osimage={{ r.stdout }}

