---
# handlers file for xcat-install
- name: Restart network interface
  command: bash -c "nmcli con down {{ network.con_name }} && nmcli con up {{ network.con_name }}"

- name: restart firewall
  service:
    name: firewalld
    state: reloaded

- name: restart xcat
  service:
    name: xcatd
    state: restarted

- name: source xcat
  shell: "source /etc/profile.d/xcat.sh"